// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyhK_RQHJkR8NC5FzJ2L38NCvl1pf1VKk',
    appId: '1:410302709481:web:bfbbb96e54c434f83cba78',
    messagingSenderId: '410302709481',
    projectId: 'fire-base-autentifikasi',
    authDomain: 'fire-base-autentifikasi.firebaseapp.com',
    databaseURL: 'https://fire-base-autentifikasi-default-rtdb.firebaseio.com',
    storageBucket: 'fire-base-autentifikasi.appspot.com',
    measurementId: 'G-VPY30XBZQW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyLgdlViJMAuq-32pnIsswTNB1AeaYZ_Y',
    appId: '1:410302709481:android:4c78f807be5640f83cba78',
    messagingSenderId: '410302709481',
    projectId: 'fire-base-autentifikasi',
    databaseURL: 'https://fire-base-autentifikasi-default-rtdb.firebaseio.com',
    storageBucket: 'fire-base-autentifikasi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCqmDmgitL8YxhOvjNfidY5HuigBmiMDs',
    appId: '1:410302709481:ios:343b7070ec110b8b3cba78',
    messagingSenderId: '410302709481',
    projectId: 'fire-base-autentifikasi',
    databaseURL: 'https://fire-base-autentifikasi-default-rtdb.firebaseio.com',
    storageBucket: 'fire-base-autentifikasi.appspot.com',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCqmDmgitL8YxhOvjNfidY5HuigBmiMDs',
    appId: '1:410302709481:ios:35e474a3ebf83ef33cba78',
    messagingSenderId: '410302709481',
    projectId: 'fire-base-autentifikasi',
    databaseURL: 'https://fire-base-autentifikasi-default-rtdb.firebaseio.com',
    storageBucket: 'fire-base-autentifikasi.appspot.com',
    iosBundleId: 'com.example.fasum.RunnerTests',
  );
}
